name: 'Setup crosstool-ng'
description: 'Install crosstool-ng and required packages'
inputs:
  version:
    description: 'ct-ng version'
    required: true
    default: '1.28.0'
runs:
  using: "composite"
  steps:
    - name: Echo action Path
      run: echo ${{github.action_path}}
      shell: bash
    - name: Install packages (Linux)
      run: | 
          sudo apt-get update && sudo apt-get install -y gcc g++ gperf bison flex texinfo help2man make libncurses5-dev \
          python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 xz-utils unzip \
          patch libstdc++6 rsync git meson ninja-build
      shell: bash
      if: ${{ runner.os == 'Linux' }}
    - name: Install packages (macOS)
      run: | 
          brew install autoconf automake bash binutils gawk gnu-sed \
            gnu-tar help2man make meson ncurses ninja pkg-config texinfo libtool
      shell: bash
      if: ${{ runner.os == 'macOS' }}
    - name: Install crosstool-ng
      run: |
        if [[ $RUNNER_OS == "macOS" ]]; then
          export PATH="$PATH:$(brew --prefix)/opt/binutils/bin"
        fi
        ${{github.action_path}}/install-crosstool.sh --prefix="$HOME/.local/"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      shell: bash