name: Build cross-compiler

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  build-linux-x64:
    runs-on: ubuntu-22.04

    steps:
      - name: Install packages
        run: | 
          sudo apt-get update && sudo apt-get install -y gcc g++ gperf bison flex texinfo help2man make libncurses5-dev \
          python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 xz-utils unzip \
          patch libstdc++6 rsync git meson ninja-build
      - uses: actions/checkout@v5
      - name: Setup crosstool-ng
        run: |
          ./install-crosstool.sh --prefix="$HOME/.local/"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: cache tarballs
        id: cache
        uses: actions/cache@v4
        with:
          path: src.tar
          key: src.tar-${{runner.os}}-${{ hashFiles('install-crosstool.sh') }}-${{ hashFiles('systemcore_defconfig') }}
      - name: extract tarballs
        run: |
          tar -xvf src.tar || true
      - name: Disable logging
        # Progress bar spams non-interactive console
        # File log dumps environment to uploaded artifact
        run: |
          cat >> systemcore_defconfig <<EOF
          # CT_LOG_PROGRESS_BAR is not set
          # CT_LOG_TO_FILE is not set
          EOF
      - name: Download toolchain sources
        run: |
          mkdir -p src
          ct-ng defconfig DEFCONFIG=systemcore_defconfig
          sed -i -e '/CT_LOG_PROGRESS_BAR/s/y$/n/' .config
          sed -i -e '/CT_LOCAL_TARBALLS_DIR/s/HOME/CT_TOP_DIR/' .config
          ct-ng source
      - name: collect tarballs
        run: |
          ./dedup-tars.sh src
          echo "archiving:"
          tar -cvf src.tar src
      - name: Save sources
        uses: actions/cache/save@v4
        with:
          path: src.tar
          key: src.tar-${{runner.os}}-${{ hashFiles('install-crosstool.sh') }}-${{ hashFiles('systemcore_defconfig') }}
      - name: Build toolchain
        run: |
          ct-ng build
      - name: Archive toolchain
        run: tar -cvzf aarch64-systemcore-linux-gnu.tar.gz aarch64-systemcore-linux-gnu/
        working-directory: /home/runner/x-tools/
      - name: Test toolchain
        run: ./test/test-toolchain.sh -a /home/runner/x-tools/aarch64-systemcore-linux-gnu.tar.gz -t aarch64-systemcore-linux-gnu -p aarch64-systemcore-linux-gnu- -l cxx -l fortran
      - name: Upload toolchain
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-systemcore-linux-gnu_x86_64-linux-gnu
          path: ~/x-tools/aarch64-systemcore-linux-gnu.tar.gz
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            artifactId: x86_64-apple-darwin
          - os: macos-14
            artifactId: aarch64-apple-darwin
    name: build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    steps:
      - name: Install packages
        run: | 
          brew install autoconf automake bash binutils gawk gnu-sed \
               gnu-tar help2man make meson ncurses ninja pkg-config texinfo libtool
      - name: create case sensitive workspace volume for macOS
        run: |
          cd ..
          rmdir crosstool-systemcore
          hdiutil create "${HOME}/Workspace.sparseimage" -volname crosstool-systemcore -type SPARSE -size 30g -fs HFSX
          hdiutil mount "${HOME}/Workspace.sparseimage" -mountroot /Users/runner/work/crosstool-systemcore
          cd crosstool-systemcore
      - uses: actions/checkout@v5
      - name: Setup crosstool-ng
        run: |
          PATH="$PATH:$(brew --prefix)/opt/binutils/bin"
          export PATH
          ./install-crosstool.sh --prefix="$HOME/.local/"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: cache tarballs
        id: cache
        uses: actions/cache@v4
        with:
          path: src.tar
          key: src.tar-${{matrix.os}}-${{ hashFiles('install-crosstool.sh') }}-${{ hashFiles('systemcore_defconfig') }}
          restore-keys: |
            src.tar-${{matrix.os}}-${{ hashFiles('install-crosstool.sh') }}-
            src.tar-${{matrix.os}}-
            src.tar-${{runner.os}}-${{ hashFiles('install-crosstool.sh') }}-
            src.tar-${{runner.os}}-
      - name: extract tarballs
        run: |
          tar -xvf src.tar || true
          touch stamp
      - name: Disable progress bar
        # Progress bar spams non-interactive console
        # File log dumps environment to uploaded artifact
        # CT_COMP_TOOLS_BISON=y
        # CT_BISON_V_3_8=y
        run: |
          cat >> systemcore_defconfig <<EOF
          # CT_LOG_PROGRESS_BAR is not set
          EOF
      - name: Download toolchain sources
        run: |
          mkdir -p src
          ct-ng defconfig DEFCONFIG=systemcore_defconfig
          sed -i -e '/CT_LOG_PROGRESS_BAR/s/y$/n/' .config
          sed -i -e '/CT_LOCAL_TARBALLS_DIR/s/HOME/CT_TOP_DIR/' .config
          sed -i -e '/CT_GDB_CROSS_PYTHON/s/y$/n/' .config # MACOS SPECIFIC
          ct-ng source
        env:
          CT_PREFIX: ${{github.workspace}}/out
      - name: collect tarballs
        run: |
          ./dedup-tars.sh src
          echo "archiving:"
          tar -cvf src.tar src
      - name: Save sources
        uses: actions/cache/save@v4
        with:
          path: src.tar
          key: src.tar-${{matrix.os}}-${{ hashFiles('install-crosstool.sh') }}-${{ hashFiles('systemcore_defconfig') }}
      - name: Build toolchain
        run: |
          ct-ng build
        env:
          CT_PREFIX: ${{github.workspace}}/out
      - name: Upload log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/build.log
      - name: Archive toolchain
        run: tar -cvzf aarch64-systemcore-linux-gnu.tar.gz aarch64-systemcore-linux-gnu/
        working-directory: out/
      - name: Test toolchain
        run: ./test/test-toolchain.sh -a ${{github.workspace}}/out/aarch64-systemcore-linux-gnu.tar.gz -t aarch64-systemcore-linux-gnu -p aarch64-systemcore-linux-gnu- -l cxx -l fortran
      - name: Upload toolchain
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-systemcore-linux-gnu_${{matrix.artifactId}}
          path: ${{github.workspace}}/out/aarch64-systemcore-linux-gnu.tar.gz
